name: build-run-tests

on:
  push:
    branches: 
      - 'master'
      - 'develop'
      - 'feature/github-actions'
   
  pull_request:
    branches: 
      - 'master'
      - 'develop'

jobs:
  test:
    runs-on: ubuntu-latest
    container: 
      image: tsukisuperior/sdl2-docker
    steps:
    - uses: actions/checkout@v2
    - name: Initialise submodules
      run: git submodule update --init --recursive
    - name: Build and run tests
      run: make test